package org.example.ReportingLayer;

import org.example.models.BlockReport;

/**
 * Interface for observers that need to be notified when a new block is processed.
 */
public interface BlockListener {

    /**
     * Invoked when a new block report has been generated by the business logic layer.
     *
     * @param report the generated report containing block and transaction data
     */
    void onBlock(BlockReport report);
}